# This file is not a full hyprland configuration.
# It is intended to be included in your main hyprland.conf.

general {
    col.active_border = rgba(dcc3f9ee) rgba(4b4c4dee) rgba(fbebc8ee) 45deg 
    col.inactive_border = rgb(4b4c4d)
    gaps_in = 7
    gaps_out = 11
    border_size = 1
}

group {
    col.border_active = $activeBorderColor
}


decoration {
    rounding = 10
    rounding_power = 3
      shadow {
      enabled = yes
      range = 16
      color = rgba(00000088)
    }
}