# This file is not a full hyprland configuration.
# It is intended to be included in your main hyprland.conf.

general {
    col.active_border = rgba(a29da2ee) rgba(05080aee) rgba(a29da2ee) 180deg 
    col.inactive_border = rgb(05080a)
    gaps_in = 4
    gaps_out = 8
    border_size = 1
}

group {
    col.border_active = rgba(b2fff3dd)
    col.border_inactive = rgb(141719)
}


decoration {
    rounding = 12
    rounding_power = 4
      shadow {
      enabled = yes
      render_power = 6
      range = 20
      color = rgba(05080a99)
    }
}

